In [1]:
import pandas as pd
import numpy as np

In [19]:
xls = pd.ExcelFile("finanace_Dashboard.xlsx")
xls.sheet_names

['Monthly_closee',
 'Dashboard',
 'Volume_By_Name',
 'Trend_Count',
 'finance_Cleaned']

In [20]:
df = pd.read_excel(
    "finanace_Dashboard.xlsx",
    sheet_name="finance_Cleaned"
)

In [21]:
df.head()

,date,open,high,low,close,volume,Name,Year,Month,Daily_Return,Trend
0,2013-02-08,15.07,15.12,14.63,14.75,8407500.0,AAL,2013,Feb,-0.019661,Down
1,2013-02-11,14.89,15.01,14.26,14.46,8882000.0,AAL,2013,Feb,-0.013140,Down
2,2013-02-12,14.45,14.51,14.10,14.27,8126000.0,AAL,2013,Feb,0.027330,Up
3,2013-02-13,14.30,14.94,14.25,14.66,10259500.0,AAL,2013,Feb,-0.045703,Down
4,2013-02-14,14.94,14.96,13.16,13.99,31879900.0,AAL,2013,Feb,0.036455,Up

In [22]:
df.shape

(1048575, 11)

In [23]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'Name', 'Year',
       'Month', 'Daily_Return', 'Trend'],
      dtype='object')

In [24]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 11 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   date          619040 non-null   datetime64[ns]
 1   open          619029 non-null   float64
 2   high          619032 non-null   float64
 3   low           619032 non-null   float64
 4   close         619040 non-null   float64
 5   volume        619040 non-null   float64
 6   name          619040 non-null   object
 7   year          1048575 non-null  int64
 8   month         1048575 non-null  object
 9   daily_return  1048575 non-null  float64
 10  trend         1048575 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(3)
memory usage: 88.0+ MB

In [26]:
df.isnull().sum()

date            429535
open            429546
high            429543
low             429543
close           429535
volume          429535
name            429535
year                 0
month                0
daily_return         0
trend                0
dtype: int64

In [27]:
num_cols = df.select_dtypes(include='number').columns
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

/tmp/ipython-input-1317444104.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [28]:
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipython-input-2373410678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [29]:
df.duplicated().sum()

np.int64(429534)

In [30]:
df = df.drop_duplicates()

In [31]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'name', 'year',
       'month', 'daily_return', 'trend'],
      dtype='object')

In [32]:
df['date'] = pd.to_datetime(df['date'])

In [34]:
df_2023 = df[df['year'] == 2023]

In [35]:
df.loc[0:5]

,date,open,high,low,close,volume,name,year,month,daily_return,trend
0,2013-02-08,15.07,15.12,14.63,14.75,8407500.0,AAL,2013,Feb,-0.019661,Down
1,2013-02-11,14.89,15.01,14.26,14.46,8882000.0,AAL,2013,Feb,-0.013140,Down
2,2013-02-12,14.45,14.51,14.10,14.27,8126000.0,AAL,2013,Feb,0.027330,Up
3,2013-02-13,14.30,14.94,14.25,14.66,10259500.0,AAL,2013,Feb,-0.045703,Down
4,2013-02-14,14.94,14.96,13.16,13.99,31879900.0,AAL,2013,Feb,0.036455,Up
5,2013-02-15,13.93,14.61,13.93,14.50,15628000.0,AAL,2013,Feb,-0.016552,Down

In [36]:
df.iloc[0:5, 0:4]

        date   open   high    low
0 2013-02-08  15.07  15.12  14.63
1 2013-02-11  14.89  15.01  14.26
2 2013-02-12  14.45  14.51  14.10
3 2013-02-13  14.30  14.94  14.25
4 2013-02-14  14.94  14.96  13.16

In [37]:
df['price_change'] = df['close'] - df['open']

In [38]:
df['trend'] = df['price_change'].apply(
    lambda x: 'Profit' if x > 0 else 'Loss'
)

In [39]:
df.groupby('name')['close'].mean()

name
A        49.212675
AAL      38.393252
AAP     132.433463
AAPL    109.066698
ABBV     60.864440
           ...
XYL      41.434095
YUM      75.451009
ZBH     105.606291
ZION     32.171790
ZTS      45.098648
Name: close, Length: 505, dtype: float64

In [40]:
df.groupby('name')['volume'].sum().sort_values(ascending=False)

name
BAC     1.178850e+11
AAPL    6.804631e+10
GE      5.302364e+10
F       4.338813e+10
FB      4.325831e+10
            ...
WLTW    4.147346e+08
AZO     3.975851e+08
MTD     2.144898e+08
BHF     1.448784e+08
APTV    9.294778e+07
Name: volume, Length: 505, dtype: float64

In [41]:
pd.pivot_table(
    df,
    values='close',
    index='name',
    columns='trend',
    aggfunc='mean'
)

trend        Loss      Profit
name
A       49.073118   49.340761
AAL     38.300785   38.485866
AAP    131.703807  133.190275
AAPL   109.102438  109.033320
ABBV    60.441384   61.215552
...           ...         ...
XYL     41.238512   41.616759
YUM     75.122496   75.754908
ZBH    105.633849  105.582600
ZION    32.073515   32.264160
ZTS     44.369525   45.894385

[505 rows x 2 columns]

In [42]:
jan = df[df['month'] == 1]
feb = df[df['month'] == 2]
merged = pd.concat([jan, feb])
merged.head()

Empty DataFrame
Columns: [date, open, high, low, close, volume, name, year, month, daily_return, trend, price_change]
Index: []

In [43]:
df.to_csv("week5_finance_cleaned.csv", index=False)